- name: ensure remote SSH access for root is disabled
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^PermitRootLogin no$'
    insertafter: '^#PermitRootLogin'
    line: 'PermitRootLogin no'
  notify:
  - restart sshd
- name: ensure firewalld is running
  systemd:
    name: firewalld
    state: started
    enabled: true
- name: ensure ssh enabled in firewalld
  firewalld:
    service: ssh
    permanent: true
    state: enabled
  notify: restart firewalld
- name: ensure http enabled in firewalld
  firewalld:
    service: http
    permanent: true
    state: enabled
  notify: restart firewalld
- name: ensure https enabled in firewalld
  firewalld:
    service: https
    permanent: true
    state: enabled
  notify: restart firewalld